from flask import Flask, request #This line is use to import the flask class from the flask module.

app = Flask(__name__) #This line creates an instance of the Flask class. The __name__ variable is a special variable in Python that holds the name of the current module. When you run a Python script, __name__ is set to "__main__". This allows Flask to know where to look for resources such as templates and static files.

@app.route("/") #This line is a decorator that tells Flask which URL should trigger the function that follows it. In this case, the "/" URL will trigger the home() function.
def home():
    return "<h1>Hello Flask</h1>"

@app.route("/about")
def about():
    return "About page"


@app.route("/submit", methods=["POST", "GET"])
def submit():
    if request.method=="POST":
        return "You are using POST method"
    else:
        return "You are using GET method"

if __name__ == "__main__":
    app.run(debug=True) #This line runs the Flask application. The debug=True argument enables debug mode, which provides helpful error messages and automatically reloads the server when code changes are made.

#request is a global variable in Flask that represents the incoming HTTP request. It contains information about the request, such as the method (GET, POST, etc.), form data, query parameters, and more. In this code, we use request.method to check whether the incoming request is a POST or GET request and return an appropriate response based on that.

#response is the output that the Flask application sends back to the client (usually a web browser) after processing a request. In this code, the response is generated by returning a string from the view functions (home(), about(), and submit()). When a client makes a request to the specified routes ("/", "/about", or "/submit"), Flask processes the request and sends back the corresponding response as defined in these functions.

#redirect is a function in Flask that allows you to redirect the user to a different URL. It is commonly used when you want to send the user to another page after they have submitted a form or when they need to be redirected to a login page. In this code snippet, we do not have any redirection implemented, but you can use the redirect function from the flask module to achieve this functionality if needed.

#url_for is a function in Flask that generates a URL for a given endpoint (view function) and any arguments that the endpoint requires. It is useful for creating URLs dynamically and helps to avoid hardcoding URLs in your templates or view functions. In this code snippet, we do not have any usage of url_for, but you can use it to generate URLs for your routes when needed.

#session is a way to store information about a user's session in Flask. It allows you to keep track of data across multiple requests from the same user. This is typically used for things like user authentication, where you want to remember that a user is logged in as they navigate through different pages of your application. In this code snippet, we do not have any usage of session, but you can use it to manage user sessions if needed.